on:
  push:
    branches:
      - master
      - dev
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy Dev Branch to Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
      with:
        ref: dev # Specify the branch name here
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.condoinhotel.com
        port: 21
        username: testuser@test.ljaskevic.com
        password: ${{ secrets.ftp_password }}
